### ISSUE TITLE
Improve grammar and spelling on any article

### ISSUE THREAD

**Issue by kevbite** [kevbite/kevbite.github.io#12]
Review an article on https://kevsoft.net and make improvements to the spelling and grammar.

**Comment by 23krishna** [comment]
I can help. Please assign me the task

**Comment by kevbite** [comment]
Hey, @23krishna feel free to pick any of the articles and review it and submit changes via a PR. Also, make sure you're not reviewing one that has already been reviewed 👍.

**Comment by 23krishna** [comment]
> Hey, @23krishna feel free to pick any of the articles and review it and submit changes via a PR. Also, make sure you're not reviewing one that has already been reviewed 👍.

okay sure

**Comment by rudyt7** [comment]
Hi I would like to work on this

**Comment by kevbite** [comment]
Hey @rudyt7 👋 please picks one of the articles and submit a PR linking in this issue. Thanks

**Comment by rudyt7** [comment]
Hi @kevbite can you add the Hacktoberfest topic in the main repo for the PR to count.

**Comment by kevbite** [comment]
Hey @rudyt7 I've added the topic so it's valid for hacktoberfest 👍

**Comment by kevbite** [comment]
Thanks, everyone!
